//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BugTrackEntities : DbContext
    {
        public BugTrackEntities()
            : base("name=BugTrackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Bug> T_Bug { get; set; }
        public DbSet<T_Comment> T_Comment { get; set; }
        public DbSet<T_Project> T_Project { get; set; }
        public DbSet<T_Transaction> T_Transaction { get; set; }
        public DbSet<T_User> T_User { get; set; }
    }
}
