//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bug
    {
        public T_Bug()
        {
            this.T_Comment = new HashSet<T_Comment>();
            this.T_Transaction = new HashSet<T_Transaction>();
        }
    
        public long id { get; set; }
        public string title { get; set; }
        public long idProject { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual T_Project T_Project { get; set; }
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual ICollection<T_Transaction> T_Transaction { get; set; }
    }
}
