//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Transaction
    {
        public long id { get; set; }
        public long idBug { get; set; }
        public long idUser { get; set; }
        public int statut { get; set; }
    
        public virtual T_Bug T_Bug { get; set; }
        public virtual T_User T_User { get; set; }
    }
}
