//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.T_Comment = new HashSet<T_Comment>();
            this.T_Transaction = new HashSet<T_Transaction>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string firstname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual ICollection<T_Transaction> T_Transaction { get; set; }
    }
}
