//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicationServiceBugTrack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bug
    {
        public long id { get; set; }
        public string title { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual T_Project T_Project { get; set; }
    }
}
