//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicationServiceBugTrack.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Project
    {
        public T_Project()
        {
            this.T_Bug = new HashSet<T_Bug>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public System.DateTime startDate { get; set; }
    
        public virtual ICollection<T_Bug> T_Bug { get; set; }
    }
}
